-- Master Table for SQL based Transactions table
CREATE TABLE XXFIN_TXN
(
	  txn_id			NUMBER GENERATED BY DEFAULT AS IDENTITY
	, gateway			VARCHAR2(120)
	, method            VARCHAR2(120)
	, description       VARCHAR2(240)
	, metadata          CLOB
	, status            VARCHAR2(20)
	, error_msg         VARCHAR2(500)
	, amount            NUMBER(38,2)
	, currency          VARCHAR2(50)
	, auth_id           VARCHAR2(120)	NOT NULL
	, source_id         NUMBER			NOT NULL
	, target_id         NUMBER          NOT NULL
	, txn_event         VARCHAR2(30)	NOT NULL
	, creation_date     DATE
	, created_by        VARCHAR2(120)
	, CONSTRAINT XXFIN_TXN_PK PRIMARY KEY(txn_id)
	, CONSTRAINT XXFIN_TXN_FK_SID FOREIGN KEY(source_id) REFERENCES XXFIN_USERS(user_id) 
	, CONSTRAINT XXFIN_TXN_FK_TID FOREIGN KEY(target_id) REFERENCES XXFIN_USERS(user_id) 
)