-- TODO: -- Master Table for SQL based Logging Events table
CREATE TABLE XXFIN_LOG_EVENTS
(
	  log_id			NUMBER GENERATED BY DEFAULT AS IDENTITY
	, object_id			NUMBER			NOT NULL
	, object_name		VARCHAR2(120)	NOT NULL
	, logging_event		VARCHAR2(120)	NOT NULL
	, creation_date		DATE			NOT NULL
	, description		VARCHAR2(240)
	, CONSTRAINT XXFIN_LE_PK PRIMARY KEY(log_id)
)