-- Master Table for SQL based Users table
CREATE TABLE XXFIN_USERS
(
	  user_id			NUMBER GENERATED BY DEFAULT AS IDENTITY
	, first_name		VARCHAR2(120)
	, last_name			VARCHAR2(120)
	, username          VARCHAR2(30)	NOT NULL
	, password          VARCHAR2(100)	NOT NULL
	, email             VARCHAR2(50)
	, mobile            VARCHAR2(20)
	, verified          VARCHAR2(5)		DEFAULT 'N'
	, mobile_verified	VARCHAR2(5)		DEFAULT 'N'
	, email_verified	VARCHAR2(5)		DEFAULT 'N'
	, creation_date		DATE
	, last_updated_date	DATE
	, balance			NUMBER(38,2)	DEFAULT 0.00
	, currency			VARCHAR2(10)
	, mfa				VARCHAR2(5)		DEFAULT 'N'
	, token				VARCHAR2(120)
	, disabled			VARCHAR2(5)		DEFAULT 'N'
	, CONSTRAINT XXFIN_USERS_PK PRIMARY KEY(user_id)
	, CONSTRAINT XXFIN_USER_USERNAME UNIQUE(USERNAME)
	, CONSTRAINT XXFIN_USER_EMAIL UNIQUE(EMAIL)
	, CONSTRAINT XXFIN_USER_MOBILE UNIQUE(MOBILE)
	, CONSTRAINT XXFIN_USERS_CHECK CHECK (EMAIL IS NOT NULL OR MOBILE IS NOT NULL)
)